#!/usr/bin/env python3
"""
Apply the metadata sweep: topics (all 54) and descriptions (the 19 missing).

MUTATES repositories. Every change is metadata only: topics and the one-line
description. No files, branches or settings are touched.

Descriptions are hand-written from the evidence pass, not generated by regex.
A regex can tell you a repo mentions "email"; it cannot tell you what the repo
is for. Where the evidence was genuinely insufficient (an empty repo), this
script declines to write a description rather than invent one.

Usage: apply_metadata.py evidence.json [--dry-run]
"""
import json
import os
import re
import subprocess
import sys
import time

SP = os.path.dirname(os.path.abspath(__file__))

# Hand-written from the README / source of each repo. Anything not listed here
# already has a description and is left exactly as the author wrote it.
DESCRIPTIONS = {
    "About-Us-Page":
        "Responsive About Us pages for Lake B2B and Champions Group companies.",
    "ChamPDF":
        "Privacy-first, self-hostable, client-side PDF toolkit. Edit, merge, split and "
        "process PDFs in the browser with no server-side handling.",
    "ChampOracle":
        "Market simulation command centre. Build a knowledge graph from an intelligence "
        "brief, run AI agents against it, and debrief the outcome before committing real "
        "resources. Runs on a self-hosted Neo4j graph.",
    "Champ_Bot":
        "Near read-only WhatsApp team memory bot for the Lake B2B team. Listens to group "
        "conversations and writes them to shared memory.",
    "Champion-Ranch-Tracking-System":
        "Champions Ranch room tracking system API.",
    "Deep_kit":
        "Your Personal AI. Locally contained, locally empowered.",
    "ICP-Finder-LLM-R1":
        "Modular Docker-based ICP generation with DeepSeek R1, n8n workflows and a Neo4j "
        "graph database.",
    "Investor-Module":
        "Investor intelligence search platform (Cadence) from Champions Infometrics, powered "
        "by the LakeB2B Data API.",
    "LakeB2B_Social_Post_Generator":
        "Frontend app for generating brand-consistent social media images for LakeB2B.",
    "Partner-Portal":
        "Partner portal for external collaborators: React Router frontend, auth-gated, with "
        "a plugin system.",
    "Social-Bot-LinkedIn-":
        "Enterprise multi-agent LinkedIn automation with AI-assisted decision making, "
        "content analysis and human-like interaction at scale.",
    "Voice-Qualified-Template":
        "Eleven Labs voice agent lead management system.",
    "champ-skills":
        "Shared agent skills for the Champions Group teams. Publishable to Claude Code, "
        "Cursor, Gemini or any skills runtime.",
    "champpreso":
        "Realtime visual brainstorming partner. Let the whiteboard whiteboard itself.",
    "gen_ui":
        "Template repository for a generative UI app powered by C1, bootstrapped with "
        "create-next-app.",
    "pikvita-mobile-app-android-fix":
        "React Native app for Pikvita, built with Expo, TypeScript and Firebase.",
    "pikvita-quiz":
        "Single-file interactive Pikvita quiz: spectrum-based questions with scored results.",
    "ChampIQ":
        "ChampIQ: a voice and canvas workspace, split into a canvas frontend and a voice "
        "service in one pnpm monorepo.",
}


def gh(path, method="GET", fields=None, timeout=45, tries=3):
    """PATCH/POST support. Retries only on transient gateway errors."""
    last = None
    for i in range(tries):
        cmd = ["gh", "api", path, "-X", method]
        if fields:
            for k, v in fields.items():
                cmd += ["-f", f"{k}={v}"]
        try:
            p = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
            if p.returncode == 0:
                return json.loads(p.stdout) if p.stdout.strip() else {}
            err = p.stderr or ""
            if any(c in err for c in ("502", "503", "504")):
                last = err
                time.sleep(1.5 * (i + 1))
                continue
            return {"__error__": err.strip()[:300]}
        except subprocess.TimeoutExpired:
            last = "timeout"
            time.sleep(1.5 * (i + 1))
    return {"__error__": last}


def main():
    ev = json.load(open(sys.argv[1]))
    dry = "--dry-run" in sys.argv

    planned = []
    for full, v in ev.items():
        changes = {}
        topics = v["derived_topics"]
        if topics:
            changes["topics"] = ",".join(topics)
        if not v["description"] and v["name"] in DESCRIPTIONS:
            changes["description"] = DESCRIPTIONS[v["name"]]
        elif not v["description"]:
            changes["description"] = None  # evidence insufficient, skip
        if changes:
            planned.append((full, v["name"], changes,
                            "description" in changes and changes["description"] is None))

    print(f"{'DRY RUN' if dry else 'APPLYING'}: {len(planned)} repos to update\n")
    ok = skipped = err = 0
    for full, name, changes, no_desc in planned:
        if no_desc:
            print(f"  skip  {name:32s} no evidence for a description")
            skipped += 1
            continue
        if dry:
            print(f"  would  {name:32s} topics={changes.get('topics','-')}")
            ok += 1
            continue
        r = gh(f"repos/{full}", "PATCH", changes)
        if "__error__" in r:
            print(f"  ERROR  {name:32s} {r['__error__'][:110]}")
            err += 1
        else:
            print(f"  ok     {name:32s} topics={r.get('topics')}")
            ok += 1
    print(f"\nok={ok} skipped={skipped} errors={err}")
    if err:
        sys.exit(1)


if __name__ == "__main__":
    main()
