#!/usr/bin/env python3
"""Regenerate INDEX.md, the README.md category counts, and each category README table
from the skill folders on disk. Run from the repo root: python3 scripts/build_index.py

Descriptions come from each SKILL.md frontmatter, flattened to one line, with em and en
dashes replaced (house rule) and cut to 170 characters to match the existing row width.
"""
import os
import re
import sys

try:
    import yaml
except ImportError:  # fall back to a minimal parser
    yaml = None

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WIDTH = 170

# folder -> (category label, one-line blurb). Order here is the order in INDEX.md.
CATEGORIES = [
    ("design/skills", "Design & Creative", "UI/UX, frontend design, decks, visuals, infographics, art"),
    ("design/brand-guidelines", "Brand Guidelines", "Official brand systems for Champions Group companies"),
    ("marketing", "Marketing & Content", "Blog, campaign, SEO, copywriting, social, thought leadership"),
    ("sales", "Sales & Outreach", "REACH stages, prospecting, negotiation, lead gen, outreach"),
    ("research", "Research & Science", "Literature review, papers, bioinformatics (AlphaFold/Boltz etc.)"),
    ("documents", "Documents & Contracts", "NDAs, docs co-authoring, one-pagers, ranch docs, reports"),
    ("engineering", "Engineering & Dev", "MCP, compute, testing, frontend build, site ops, webapps"),
    ("software-development", "Software Development", "Workspace builds, release and integration engineering"),
    ("productivity", "Productivity & Meetings", "Daily notes, meetings, planners, onboarding, interviews, quizzes"),
    ("vault", "Vault & KM", "Celsus knowledge management, memory, linking, habits"),
]
SKIP_TOP = {".git", "scripts", ".marketplace"}


def clean(text):
    text = re.sub(r"\s+", " ", str(text or "")).strip()
    text = text.replace(" — ", ", ").replace("—", ", ").replace(" – ", ", ").replace("–", "-")
    text = text.replace("|", "/")
    return text[:WIDTH]


def frontmatter(path):
    raw = open(path, encoding="utf-8", errors="ignore").read()
    m = re.match(r"^---\s*\n(.*?)\n---", raw, re.S)
    if not m:
        return {}
    block = m.group(1)
    if yaml:
        try:
            data = yaml.safe_load(block)
            if isinstance(data, dict):
                return data
        except Exception:
            pass
    data = {}
    for key in ("name", "description"):
        mm = re.search(rf"^{key}:\s*(.*?)(?=^\w[\w-]*:|\Z)", block, re.M | re.S)
        if mm:
            val = mm.group(1).strip()
            if val[:1] in (">", "|"):
                val = val[1:].lstrip("-+")
            data[key] = val.strip().strip('"').strip("'")
    return data


def collect():
    """Return {folder: [(skill, desc, relpath)]} plus root-level strays."""
    found = {c[0]: [] for c in CATEGORIES}
    strays = []
    for folder, _, _ in CATEGORIES:
        base = os.path.join(ROOT, folder)
        if not os.path.isdir(base):
            continue
        for name in sorted(os.listdir(base)):
            skill_md = os.path.join(base, name, "SKILL.md")
            if os.path.isfile(skill_md):
                fm = frontmatter(skill_md)
                found[folder].append((name, clean(fm.get("description")), f"{folder}/{name}"))
    for name in sorted(os.listdir(ROOT)):
        if name in SKIP_TOP or name.startswith("."):
            continue
        if os.path.isfile(os.path.join(ROOT, name, "SKILL.md")):
            fm = frontmatter(os.path.join(ROOT, name, "SKILL.md"))
            strays.append((name, clean(fm.get("description")), name))
    return found, strays


def table(rows, with_cat=None):
    if with_cat:
        out = ["| Skill | Category | What it does |", "|---|---|---|"]
        out += [f"| `{n}` | {c} | {d} |" for n, c, d in rows]
    else:
        out = ["| Skill | What it does |", "|---|---|"]
        out += [f"| `{n}` | {d} |" for n, d, _ in rows]
    return "\n".join(out)


def main():
    found, strays = collect()
    label = {f: l for f, l, _ in CATEGORIES}
    if strays:
        found.setdefault("engineering", [])
    total = sum(len(v) for v in found.values()) + len(strays)
    used = [c for c in CATEGORIES if found.get(c[0])]

    flat = []
    for folder, lab, _ in CATEGORIES:
        flat += [(n, lab, d) for n, d, _ in found.get(folder, [])]
    flat += [(n, "Engineering & Dev", d) for n, d, _ in strays]
    flat.sort(key=lambda r: (r[1] != "Design & Creative", [c[1] for c in CATEGORIES].index(r[1]), r[0]))

    parts = [
        "# Champ Skills Index",
        "",
        "Searchable index of every skill in this repo. Each skill is a self-contained folder with a `SKILL.md` entry point. `skill-creator` can also compose new skills. This file is generated by `scripts/build_index.py`; edit the skills, not this file.",
        "",
        f"**{total} skills** across **{len(used)} categories**.",
        "",
        "## All skills (flat)",
        "",
        table(flat, with_cat=True),
        "",
    ]
    for folder, lab, blurb in CATEGORIES:
        rows = found.get(folder, [])
        if folder == "engineering":
            rows = rows + strays
        if not rows:
            continue
        parts += [f"## {lab} (`{folder}/`)", "", blurb + ".", "", table(sorted(rows)), ""]
    parts += [
        "## Install from a skill folder",
        "```bash",
        "git clone https://github.com/Champ-Deep/champ-skills.git",
        "cp -R champ-skills/design/skills/frontend-design ~/.claude/skills/",
        "```",
        "",
        "No em dashes.",
        "",
    ]
    open(os.path.join(ROOT, "INDEX.md"), "w", encoding="utf-8").write("\n".join(parts))

    # README.md: total line and category table
    readme_p = os.path.join(ROOT, "README.md")
    readme = open(readme_p, encoding="utf-8").read()
    readme = re.sub(r"\*\*\d+ skills\*\* across \d+ categories", f"**{total} skills** across {len(used)} categories", readme)
    readme = re.sub(r"searchable index of all \d+ skills", f"searchable index of all {total} skills", readme)
    rows = ["| Category | Folder | What's inside | Count |", "|---|---|---|---|"]
    for folder, lab, blurb in used:
        n = len(found[folder]) + (len(strays) if folder == "engineering" else 0)
        rows.append(f"| {lab} | `{folder}/` | {blurb} | {n} |")
    readme = re.sub(r"\| Category \| Folder \|.*?(?=\n\n)", "\n".join(rows), readme, count=1, flags=re.S)
    open(readme_p, "w", encoding="utf-8").write(readme)

    # Category READMEs: regenerate only the skill table, keep the prose above it
    for folder, lab, _ in CATEGORIES:
        p = os.path.join(ROOT, folder, "README.md")
        if not os.path.isfile(p) or not found.get(folder):
            continue
        txt = open(p, encoding="utf-8").read()
        new_tbl = table(found[folder])
        txt2 = re.sub(r"\| Skill \| What it does \|\n\|---\|---\|\n(?:\|.*\|\n?)*", new_tbl + "\n", txt, count=1)
        if txt2 != txt:
            open(p, "w", encoding="utf-8").write(txt2)

    print(f"INDEX.md rebuilt: {total} skills, {len(used)} categories")
    if strays:
        print("Root-level skill folders (listed under Engineering & Dev): " + ", ".join(s[0] for s in strays))


if __name__ == "__main__":
    sys.exit(main())
